name: matheus leston
favicon: null
layout_spectrum: 0.6632896193768829
typography_spectrum: 0.9355018916539848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.35861415951512754
  lightness: 0.7440460422076285
  saturation: 0.9116307673975825
  rhythmicContrast: 0.1612105725798756
purpose: []
