name: matheus leston
favicon: null
layout_spectrum: 0.74966
typography_spectrum: 0.9355018916539848
title: matheus leston
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#493f36'
    - '#89785c'
    - '#e1d9d6'
    - '#e0a488'
  brandStrength: 0.35861415951512754
  lightness: 0.7440460422076285
  saturation: 0.9375
  rhythmicContrast: 0.1612105725798756
purpose: []
